### ISSUE TITLE
ICEE poster

### ISSUE THREAD

**Issue by frksteenhoff** [frksteenhoff/ClimApp#119]
Poster presentation date: 8th of July
Presentation time: 2:30PM-3:00PM

**TODO**
* [x] Agree on content
* [x] Create draft
* [x] Get draft reviewed
* [x] Adopt changes after review
* [x]  Print

**Comment by frksteenhoff** [comment]
Printed and completed Friday the 5th.
