### ISSUE TITLE
Design of user feedback interface

### ISSUE THREAD

**Issue by frksteenhoff** [frksteenhoff/ClimApp#40]
User feedback and testing methods 

**In-app:**
* Through notifications
* In its own module

*Intervals*:
* Daily (morning or evening)
* At customizable times

**In person:**
* Wizard of Oz
* Think out loud
*

**To-do:**
- [x] Decide upon feedback type (do this through in person testing + methods suggested in articles)
- [x] Decide upon layout (ask Jakob Eg/Per Bækgaard for feedback on design)
- [x] Create feedback flow diagram (need all possible scenarios for user to map to feedback questions)

**Comment by frksteenhoff** [comment]
Currently started creating something in the line of this:
![image](https://user-images.githubusercontent.com/6978512/53641786-47127700-3c30-11e9-80d7-75d3739717ba.png)

**Comment by FritzdorfSport** [comment]
Those screen shots look really nice!
