### ISSUE TITLE
Create thesis project plan

### ISSUE THREAD

**Issue by frksteenhoff** [frksteenhoff/ClimApp#41]
Related to issue #44, project timeline.

- [x] Describe work for each month
- [x] Outline tests and development
- [x] Give rough estimate on time frame 
- [x] Remember to also add periods for writing
- [x] Include time to write abstract for ICEE
- [x] Remember that some days in early June will be used at the ICEE conference.
- [x] Sign-off from @BorisKingma on #44
