### ISSUE TITLE
Implement feedback module in Cordova app

### ISSUE THREAD

**Issue by frksteenhoff** [frksteenhoff/ClimApp#54]
Implement in Cordova framework (should look something like this: https://github.com/katzer/cordova-plugin-local-notifications)

**TODO**
* [x] Create notification prompting user to provide feedback
* [x] Handle errors in api scheduling notification at wrong times/not as in documentation
* [x] Create page the user should be redirected to when clicking on notification
* [x] Add action buttons `Open/Dismiss` (currently not showing in Android app even though code is implemented)
* [x] Implement redirect in notification (missing as this implementation is not clear from the documentation)
* [x] Create static content on notification page (later make feedback content dependent on content from database chosen based on user's situation) related to issue #40, feedback flow chart.
* [x] Add different notification icon (`smallIcon` than default bell (need image)
* [x] Agree on logic deciding when to schedule notification @BorisKingma (**as mentioned in several pull requests, the notifications plugin is currently not working, need help on this.**)

**Read related articles from Jakob Eg**
* http://web.mit.edu/bentley/www/papers/reminders-note-forAC.pdf
* https://www.smunson.com/portfolio/projects/lifelogs/deviceinthedrawer_ubi16.pdf

**Comment by frksteenhoff** [comment]
Currently this is how the feedback looks -- I will try to customize it now.
![image](https://user-images.githubusercontent.com/6978512/54606470-3a718980-4a4c-11e9-8742-1a72241b928c.png)

**Comment by frksteenhoff** [comment]
@BorisKingma need concrete logic to decide whether or not to schedule a notification. Currently the functionality is commented out as we want to avoid a recurring notification.

**Comment by frksteenhoff** [comment]
As mentioned in the description the logic for handling redirect and the time for the notification to appear is not done. 
However it is possible to get feedback on how the feedback module looks/feels as a reference to it is added on the `Settings` screen in the app.

**Comment by frksteenhoff** [comment]
The notifications are not triggered when the app is closed. This needs to be handleded.
